version: 2

# Main build configuration
builds:
  - id: kproxy
    main: ./cmd/kproxy
    binary: kproxy
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
    targets:
      - linux_amd64
      - linux_arm64
      - linux_arm_7
      - darwin_amd64
      - darwin_arm64
      - windows_amd64

# Archive configuration for GitHub releases
archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - docs/README.md
      - LICENSE
      - configs/config.example.yaml

# Linux packages (DEB and RPM)
nfpms:
  - id: kproxy-packages
    package_name: kproxy
    ids:
      - kproxy
    file_name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    vendor: GoodTune
    homepage: https://github.com/goodtune/kproxy
    maintainer: GoodTune <kproxy@goodtune.io>
    description: |
      KProxy - Transparent HTTP/HTTPS interception proxy for home network parental controls.
      Combines DNS-level routing with proxy-level policy enforcement, dynamic TLS certificate
      generation, and usage tracking.
    license: MIT
    section: net
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin

    # Package contents
    contents:
      # Binary (already included by default in bindir)

      # Configuration file
      - src: configs/config.yaml
        dst: /etc/kproxy/config.yaml
        type: config|noreplace
        file_info:
          mode: 0644

      # Example configuration
      - src: configs/config.example.yaml
        dst: /etc/kproxy/config.example.yaml
        file_info:
          mode: 0644

      # Policy files (marked as config to prevent overwrite on upgrade)
      - src: policies/config.rego
        dst: /etc/kproxy/policies/config.rego
        type: config|noreplace
        file_info:
          mode: 0644

      - src: policies/device.rego
        dst: /etc/kproxy/policies/device.rego
        file_info:
          mode: 0644

      - src: policies/dns.rego
        dst: /etc/kproxy/policies/dns.rego
        file_info:
          mode: 0644

      - src: policies/proxy.rego
        dst: /etc/kproxy/policies/proxy.rego
        file_info:
          mode: 0644

      - src: policies/helpers.rego
        dst: /etc/kproxy/policies/helpers.rego
        file_info:
          mode: 0644

      # Systemd units
      - src: systemd/kproxy.service
        dst: /lib/systemd/system/kproxy.service
        file_info:
          mode: 0644

      - src: systemd/kproxy.socket
        dst: /lib/systemd/system/kproxy.socket
        file_info:
          mode: 0644

      # Branding assets
      - src: assets/kproxy-logo.png
        dst: /usr/share/kproxy/assets/kproxy-logo.png
        file_info:
          mode: 0644

      # CA certificate directory
      - dst: /etc/kproxy/ca
        type: dir
        file_info:
          mode: 0755
          owner: kproxy
          group: kproxy

      # Database directory
      - dst: /var/lib/kproxy
        type: dir
        file_info:
          mode: 0755
          owner: kproxy
          group: kproxy

      # Log directory
      - dst: /var/log/kproxy
        type: dir
        file_info:
          mode: 0755
          owner: kproxy
          group: kproxy

    # Scripts
    scripts:
      preinstall: scripts/preinstall.sh
      postinstall: scripts/postinstall.sh
      preremove: scripts/preremove.sh

    # Dependencies
    dependencies:
      - ca-certificates

    # RPM-specific
    rpm:
      group: System/Daemons
      summary: HTTP/HTTPS interception proxy for parental controls
      compression: lzma

    # DEB-specific
    deb:
      compression: xz

# Checksum configuration
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Snapshot configuration for non-tagged builds
snapshot:
  version_template: "{{ .Version }}-next"

# Changelog configuration
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Security Updates'
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Others
      order: 999

# GitHub release configuration
release:
  github:
    owner: goodtune
    name: kproxy
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## KProxy {{ .Version }}

    ### Installation

    #### Linux (Debian/Ubuntu)
    ```bash
    wget https://github.com/goodtune/kproxy/releases/download/{{ .Tag }}/kproxy_{{ .Version }}_linux_x86_64.deb
    sudo dpkg -i kproxy_{{ .Version }}_linux_x86_64.deb
    ```

    #### Linux (RHEL/CentOS/Fedora)
    ```bash
    wget https://github.com/goodtune/kproxy/releases/download/{{ .Tag }}/kproxy_{{ .Version }}_linux_x86_64.rpm
    sudo rpm -i kproxy_{{ .Version }}_linux_x86_64.rpm
    ```

    #### macOS
    ```bash
    wget https://github.com/goodtune/kproxy/releases/download/{{ .Tag }}/kproxy_{{ .Version }}_Darwin_x86_64.tar.gz
    tar -xzf kproxy_{{ .Version }}_Darwin_x86_64.tar.gz
    sudo install -m 755 kproxy /usr/local/bin/
    ```

    #### Windows
    Download the appropriate .zip file and extract it to your preferred location.

    ### What's Changed
  footer: |
    **Full Changelog**: https://github.com/goodtune/kproxy/compare/{{ .PreviousTag }}...{{ .Tag }}
